---
development:
  cloud_name: dmqyv6xea
  api_key: '288984574821474'
  api_secret: 2_57QxKO4_T1nWmVCSmuxQxVdVA
  enhance_image_tag: true
  static_file_support: false
production:
  cloud_name: dmqyv6xea
  api_key: '288984574821474'
  api_secret: 2_57QxKO4_T1nWmVCSmuxQxVdVA
  enhance_image_tag: true
  static_file_support: true
test:
  cloud_name: dmqyv6xea
  api_key: '288984574821474'
  api_secret: 2_57QxKO4_T1nWmVCSmuxQxVdVA
  enhance_image_tag: true
  static_file_support: false
